Completed second homework
LordDmitry/external-courses pull request #3
Opened 2018-10-04 08:52 UTC by LordDmitry

2018-10-05 11:58 UTC, komarikl requested changes

2018-10-05 11:58 UTC, komarikl commented on src/ex2_js-basics-part2/task-01.js
> +    return result;
можно просто `return undefined`

2018-10-05 11:58 UTC, komarikl commented on src/ex2_js-basics-part2/task-05.js
> +    for (i = 1; i < someArray.length; i++){
`for (var i = 1; i < someArray.length; i++){` прям здесь лучше объявлять

2018-10-05 11:58 UTC, komarikl commented on src/homework-2/task-01.js
> +'use strict';
походу лишний файл? надо удалить

2018-10-05 12:09 UTC, LordDmitry commented on src/ex2_js-basics-part2/task-05.js
> +    for (i = 1; i < someArray.length; i++){
На это ругреться,  говорит что инициализироваты переменные нужно в начале функции. Мне так тоже не нравится.

2018-10-05 12:10 UTC, LordDmitry commented on src/ex2_js-basics-part2/task-01.js
> +    return result;
Тогда 2 раза return, что затруднит понимание кода имхо

2018-10-07 11:25 UTC, komarikl approved these changes

2018-10-07 11:28 UTC, komarikl approved these changes

2018-10-07 11:28 UTC, merged